[project]
name = "ncode-ext"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "colorama>=0.4.6",
    "pylightxl>=1.61",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "nuitka>=2.6.4",
]

